SELECT * FROM STUDENTS

SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'K%'
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_____'
SELECT * FROM STUDENTS WHERE CITY LIKE '_____A'
SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%TEL'
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'HA%T'
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_____' AND WEBSITE IS NULL
SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%JER%'
SELECT * FROM STUDENTS WHERE CITY LIKE 'R%' OR CITY LIKE 'B%' 
SELECT * FROM STUDENTS WHERE WEBSITE IS NOT NULL
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '[A-H]%'
SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'
SELECT * FROM STUDENTS WHERE CITY LIKE '%ROD%'
SELECT * FROM STUDENTS WHERE WEBSITE LIKE 'BI%'
SELECT CITY FROM STUDENTS WHERE LASTNAME LIKE '______' 
SELECT * FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'
SELECT * FROM STUDENTS WHERE DIVISION LIKE'II%'
SELECT FIRSTNAME FROM STUDENTS WHERE DIVISION LIKE '%BC%'
SELECT STUID,CITY FROM STUDENTS WHERE DIVISION LIKE '______' AND WEBSITE NOT LIKE NULL
SELECT * FROM STUDENTS WHERE FIRSTNAME NOT LIKE '__[A,E,I,O,U]%'